# Generated by Django 4.0.1 on 2022-02-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vote",
            options={
                "get_latest_by": "-vote_time",
                "ordering": ["-vote_time"],
                "verbose_name": "vote",
                "verbose_name_plural": "votes",
            },
        ),
    ]
