# Generated by Django 4.0.1 on 2022-02-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0002_alter_vote_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="experience",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Experience"
            ),
        ),
    ]
