version: '3'

services:
  db:
    image: postgres
    env_file: ./api/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
  api:
    build: ./api
    env_file: ./api/.env
    ports:
      - "80:8000"
    volumes:
      - ./api:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

volumes:
  db_data: