version: '3'

services:
  db:
    image: postgres:13
    env_file: ./api/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432

  redis:
    image: redis
    volumes:
      - redis_data:/data
    expose:
      - 6379

  api:
    build: ./api
    image: rankrise_api
    env_file: ./api/.env
    ports:
      - "80:8000"
      - 3000:3000
    volumes:
      - ./api:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis

volumes:
  db_data:
  redis_data: