# Generated by Django 4.0.1 on 2022-02-02 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_alter_category_options"),
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="category.category",
                verbose_name="category",
            ),
        ),
    ]
