# Generated by Django 4.0.1 on 2022-02-02 18:02

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": [django.db.models.functions.text.Upper("name")],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
    ]
